CREATE DATABASE IF NOT EXISTS authdb;
CREATE DATABASE IF NOT EXISTS restaurantdb;

GRANT ALL PRIVILEGES ON authdb.* TO 'auth'@'%';
GRANT ALL PRIVILEGES ON restaurantdb.* TO 'auth'@'%';
FLUSH PRIVILEGES;
